apiVersion: v1
kind: Service
metadata:
  name: belote-api-service
  namespace: belote
  labels:
    app: belote-api-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: belote-api-app
  type: NodePort
