apiVersion: apps/v1
kind: Deployment
metadata:
  name: belote-front-deployment
  namespace: belote
  labels:
    app: belote-front-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belote-front-app
  template:
    metadata:
      labels:
        app: belote-front-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: belote-front-deployment
          image: samsja/belote-front:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: belote-front-config
          ports:
          - containerPort: 8000


          livenessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 2


          # resources:
          #   limits:
          #     cpu: "0.2"
          #     memory: 100Mi
          #   requests:
          #     cpu: "0.1"
          #     memory: 50Mi
