apiVersion: v1
kind: Service
metadata:
  name: belote-front-service
  namespace: belote
  labels:
    app: belote-front-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: belote-front-app
  type: NodePort
